### ISSUE TITLE
Add link to web version of it.

### ISSUE THREAD

**Issue by elenavolpato** [fuzue/seasonalfood-site#7]
![Image](https://github.com/fuzue/seasonalfood-site/assets/272892/c1d2d88b-5bf4-4a13-933b-359af346fd0f)

 * Icon Web = "Use it online"

Suggest an icon

**Comment by elenavolpato** [comment]
I added the link, but what link should I put in the <a> ? I used fuzue.tech/seasonalfood/ but it is returning 404.

**Comment by aivuk** [comment]
Click on the eyes => [👀](https://github.com/fuzue/seasonalfood-site/commit/180e25cad21c993b2d71ed40b6269453429543ed#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R79)
